/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as HomeWishesRouteImport } from './routes/_home/wishes'
import { Route as HomeHomeRouteImport } from './routes/_home/home'
import { Route as HomeProfileIndexRouteImport } from './routes/_home/profile/index'
import { Route as HomeWishIdRouteImport } from './routes/_home/wish.$id'
import { Route as HomeProfileIdRouteImport } from './routes/_home/profile/$id'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const HomeWishesRoute = HomeWishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeHomeRoute = HomeHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProfileIndexRoute = HomeProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeWishIdRoute = HomeWishIdRouteImport.update({
  id: '/wish/$id',
  path: '/wish/$id',
  getParentRoute: () => HomeRouteRoute,
} as any)
const HomeProfileIdRoute = HomeProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => HomeRouteRoute,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeHomeRoute
  '/wishes': typeof HomeWishesRoute
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/profile/$id': typeof HomeProfileIdRoute
  '/wish/$id': typeof HomeWishIdRoute
  '/profile': typeof HomeProfileIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeHomeRoute
  '/wishes': typeof HomeWishesRoute
  '/about': typeof PublicAboutRoute
  '/': typeof PublicIndexRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/profile/$id': typeof HomeProfileIdRoute
  '/wish/$id': typeof HomeWishIdRoute
  '/profile': typeof HomeProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_home/home': typeof HomeHomeRoute
  '/_home/wishes': typeof HomeWishesRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/_home/profile/$id': typeof HomeProfileIdRoute
  '/_home/wish/$id': typeof HomeWishIdRoute
  '/_home/profile/': typeof HomeProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/wishes'
    | '/about'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/profile/$id'
    | '/wish/$id'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/wishes'
    | '/about'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/profile/$id'
    | '/wish/$id'
    | '/profile'
  id:
    | '__root__'
    | '/_home'
    | '/_auth'
    | '/_public'
    | '/_home/home'
    | '/_home/wishes'
    | '/_public/about'
    | '/_public/'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/_home/profile/$id'
    | '/_home/wish/$id'
    | '/_home/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_home/wishes': {
      id: '/_home/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof HomeWishesRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/home': {
      id: '/_home/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeHomeRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/profile/': {
      id: '/_home/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HomeProfileIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/wish/$id': {
      id: '/_home/wish/$id'
      path: '/wish/$id'
      fullPath: '/wish/$id'
      preLoaderRoute: typeof HomeWishIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_home/profile/$id': {
      id: '/_home/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof HomeProfileIdRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeHomeRoute: typeof HomeHomeRoute
  HomeWishesRoute: typeof HomeWishesRoute
  HomeProfileIdRoute: typeof HomeProfileIdRoute
  HomeWishIdRoute: typeof HomeWishIdRoute
  HomeProfileIndexRoute: typeof HomeProfileIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeHomeRoute: HomeHomeRoute,
  HomeWishesRoute: HomeWishesRoute,
  HomeProfileIdRoute: HomeProfileIdRoute,
  HomeWishIdRoute: HomeWishIdRoute,
  HomeProfileIndexRoute: HomeProfileIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
